/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversirupiah;

/**
 *
 * @author Alhamdulillah
 */

class comp{
    public double awal;

    public double getAwal() {
        return awal;
    }

    public void setAwal(double awal) {
        this.awal = awal;
    }
    
}

public class KonverterSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KonverterSuhu
     */
    public KonverterSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        konversi = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();
        suhu1 = new javax.swing.JTextField();
        suhu2 = new javax.swing.JTextField();
        combobox1 = new javax.swing.JComboBox<>();
        combobox2 = new javax.swing.JComboBox<>();
        kembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(165, 253, 219));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 178, 178));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Konverter Suhu");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prop/Temperature.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        konversi.setBackground(new java.awt.Color(0, 204, 204));
        konversi.setText("Konversi");
        konversi.setToolTipText("");
        konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiActionPerformed(evt);
            }
        });
        jPanel1.add(konversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 164, -1, -1));

        bersihkan.setBackground(new java.awt.Color(0, 204, 204));
        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });
        jPanel1.add(bersihkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 164, -1, -1));

        suhu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhu1ActionPerformed(evt);
            }
        });
        jPanel1.add(suhu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 124, 274, -1));

        suhu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhu2ActionPerformed(evt);
            }
        });
        jPanel1.add(suhu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 210, 274, -1));

        combobox1.setBackground(new java.awt.Color(0, 204, 204));
        combobox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin", "Reamur" }));
        combobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox1ActionPerformed(evt);
            }
        });
        jPanel1.add(combobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 124, -1, -1));

        combobox2.setBackground(new java.awt.Color(0, 204, 204));
        combobox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin", "Reamur" }));
        combobox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox2ActionPerformed(evt);
            }
        });
        jPanel1.add(combobox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 210, -1, -1));

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 262, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prop/ae83340d-0ec7-4ef7-94d4-973c8f75125d.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 500, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void suhu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suhu2ActionPerformed

    private void suhu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suhu1ActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        suhu1.setText("");
        suhu2.setText("");
    }//GEN-LAST:event_bersihkanActionPerformed

    private void konversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiActionPerformed
        String box1 = (String) combobox1.getSelectedItem();
        String box2 = (String) combobox2.getSelectedItem();
        comp komponen = new comp();
        komponen.setAwal(Double.parseDouble(suhu1.getText()));
        

        if (box1.equals("Celsius")) {
            if (box2.equals("Fahrenheit")) {
                double F = (double) ((komponen.getAwal() * (9 / 5)) + 32);
                suhu2.setText(String.valueOf(F));
            } else if (box2.equals("Kelvin")) {
                double K = (double) (komponen.getAwal() + 273);
                suhu2.setText(String.valueOf(K));
            } else if (box2.equals("Reamur")) {
                double R = (double) (komponen.getAwal() * (4 / 5));
                suhu2.setText(String.valueOf(R));
            } else if (box2.equals("Celsius")) {
                suhu2.setText(String.valueOf(komponen.getAwal()));
            }

        } else if (box1.equals("Kelvin")) {
            if (box2.equals("Fahrenheit")) {
                double F = (double) ((komponen.getAwal() - 273) * (9 / 5) + 32);
                suhu2.setText(String.valueOf(F));
            } else if (box2.equals("Kelvin")) {
                suhu2.setText(String.valueOf(komponen.getAwal()));
            } else if (box2.equals("Reamur")) {
                double R = (double) ((komponen.getAwal() - 273) * (4 / 5));
                suhu2.setText(String.valueOf(R));
            } else if (box2.equals("Celsius")) {
                double C = (double) (komponen.getAwal() - 273);
                suhu2.setText(String.valueOf(C));
            }
        } else if (box1.equals("Reamur")) {
            if (box2.equals("Fahrenheit")) {
                double F = (double) ((komponen.getAwal() * (9 / 4)) + 32);
                suhu2.setText(String.valueOf(F));
            } else if (box2.equals("Kelvin")) {
                double K = (double) (komponen.getAwal() * ((5 / 4) + 273));
                suhu2.setText(String.valueOf(K));
            } else if (box2.equals("Reamur")) {
                suhu2.setText(String.valueOf(komponen.getAwal()));
            } else if (box2.equals("Celsius")) {
                double C = (double) (komponen.getAwal() * (5 / 4));
                suhu2.setText(String.valueOf(C));
            }
        } else if (box1.equals("Fahrenheit")) {
            if (box2.equals("Fahrenheit")) {
                suhu2.setText(String.valueOf(komponen.getAwal()));
            } else if (box2.equals("Kelvin")) {
                double K = (double) (((komponen.getAwal() - 32) * (9 / 5)) + 273);
                suhu2.setText(String.valueOf(K));
            } else if (box2.equals("Reamur")) {
                double R = (double) ((komponen.getAwal() - 32) * (9 / 4));
                suhu2.setText(String.valueOf(R));
            } else if (box2.equals("Celsius")) {
                double C = (double) ((komponen.getAwal() - 32) * (9 / 5));
                suhu2.setText(String.valueOf(C));
            }
        }
    }//GEN-LAST:event_konversiActionPerformed

    private void combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox1ActionPerformed

    private void combobox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonverterSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonverterSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkan;
    private javax.swing.JComboBox<String> combobox1;
    private javax.swing.JComboBox<String> combobox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton konversi;
    private javax.swing.JTextField suhu1;
    private javax.swing.JTextField suhu2;
    // End of variables declaration//GEN-END:variables
}
