/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversirupiah;

/**
 *
 * @author Alhamdulillah
 */

class com{
    public double awal;

    public double getAwal() {
        return awal;
    }

    public void setAwal(double awal) {
        this.awal = awal;
    }
    
}

public class KonverterPanjang extends javax.swing.JFrame {

    /**
     * Creates new form KonverterPanjang
     */
    public KonverterPanjang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        panjang1 = new javax.swing.JTextField();
        panjang2 = new javax.swing.JTextField();
        bersihkan = new javax.swing.JButton();
        konversi = new javax.swing.JButton();
        combobox1 = new javax.swing.JComboBox<>();
        combobox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(183, 183, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));

        jLabel1.setBackground(new java.awt.Color(66, 66, 0));
        jLabel1.setFont(new java.awt.Font("Sitka Display", 0, 48)); // NOI18N
        jLabel1.setText("Konverter Panjang");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prop/Ruler.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 262, -1, -1));

        panjang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjang1ActionPerformed(evt);
            }
        });
        jPanel1.add(panjang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 300, -1));
        jPanel1.add(panjang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 300, -1));

        bersihkan.setBackground(new java.awt.Color(153, 153, 0));
        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });
        jPanel1.add(bersihkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 160, -1, -1));

        konversi.setBackground(new java.awt.Color(153, 153, 0));
        konversi.setText("Konversi");
        konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiActionPerformed(evt);
            }
        });
        jPanel1.add(konversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 160, -1, -1));

        combobox1.setBackground(new java.awt.Color(153, 153, 0));
        combobox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KM", "HM", "DAM", "M", "DM", "CM", "MM" }));
        jPanel1.add(combobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 120, -1, -1));

        combobox2.setBackground(new java.awt.Color(153, 153, 0));
        combobox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KM", "HM", "DAM", "M", "DM", "CM", "MM" }));
        jPanel1.add(combobox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 210, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 102, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 95, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 120, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 194, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prop/fd31f19f-b058-4803-aa12-336725026bb1.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void panjang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panjang1ActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        panjang1.setText("");
        panjang2.setText("");
    }//GEN-LAST:event_bersihkanActionPerformed

    private void konversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiActionPerformed
        String box1 = (String) combobox1.getSelectedItem();
        String box2 = (String) combobox2.getSelectedItem();
        com komponen = new com();
        komponen.setAwal(Double.parseDouble(panjang1.getText()));
        
        if (box1.equals("KM")){
            if (box2.equals("KM")){
                double hasil = komponen.getAwal();
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("HM")){
                double hasil = komponen.getAwal() * 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAM")){
                double hasil = komponen.getAwal() * 100;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("M")){
                double hasil = komponen.getAwal() * 1000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DM")){
                double hasil = komponen.getAwal() * 10000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("CM")){
                double hasil = komponen.getAwal() * 100000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("MM")){
                double hasil = komponen.getAwal() * 1000000;
                panjang2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("HM")){
            if (box2.equals("KM")){
                double hasil = komponen.getAwal() / 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("HM")){
                double hasil = komponen.getAwal();
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAM")){
                double hasil = komponen.getAwal() * 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("M")){
                double hasil = komponen.getAwal() * 100;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DM")){
                double hasil = komponen.getAwal() * 1000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("CM")){
                double hasil = komponen.getAwal() * 10000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("MM")){
                double hasil = komponen.getAwal() * 100000;
                panjang2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("DAM")){
            if (box2.equals("KM")){
                double hasil = komponen.getAwal() / 100;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("HM")){
                double hasil = komponen.getAwal() / 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAM")){
                double hasil = komponen.getAwal();
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("M")){
                double hasil = komponen.getAwal() * 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DM")){
                double hasil = komponen.getAwal() * 100;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("CM")){
                double hasil = komponen.getAwal() * 1000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("MM")){
                double hasil = komponen.getAwal() * 10000;
                panjang2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("M")){
            if (box2.equals("KM")){
                double hasil = komponen.getAwal() / 1000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("HM")){
                double hasil = komponen.getAwal() / 100;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAM")){
                double hasil = komponen.getAwal()  / 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("M")){
                double hasil = komponen.getAwal();
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DM")){
                double hasil = komponen.getAwal() * 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("CM")){
                double hasil = komponen.getAwal() * 100;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("MM")){
                double hasil = komponen.getAwal() * 1000;
                panjang2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("DM")){
            if (box2.equals("KM")){
                double hasil = komponen.getAwal() / 10000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("HM")){
                double hasil = komponen.getAwal() / 1000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAM")){
                double hasil = komponen.getAwal() / 100;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("M")){
                double hasil = komponen.getAwal() / 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DM")){
                double hasil = komponen.getAwal();
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("CM")){
                double hasil = komponen.getAwal() * 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("MM")){
                double hasil = komponen.getAwal() * 100;
                panjang2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("CM")){
            if (box2.equals("KM")){
                double hasil = komponen.getAwal() / 100000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("HM")){
                double hasil = komponen.getAwal() / 10000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAM")){
                double hasil = komponen.getAwal() / 1000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("M")){
                double hasil = komponen.getAwal() / 100;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DM")){
                double hasil = komponen.getAwal() / 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("CM")){
                double hasil = komponen.getAwal();
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("MM")){
                double hasil = komponen.getAwal() * 10;
                panjang2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("MM")){
            if (box2.equals("KM")){
                double hasil = komponen.getAwal() / 1000000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("HM")){
                double hasil = komponen.getAwal() / 100000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAM")){
                double hasil = komponen.getAwal() / 10000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("M")){
                double hasil = komponen.getAwal() / 1000;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("DM")){
                double hasil = komponen.getAwal() / 100;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("CM")){
                double hasil = komponen.getAwal() / 10;
                panjang2.setText(String.valueOf(hasil));
            } else if (box2.equals("MM")){
                double hasil = komponen.getAwal();
                panjang2.setText(String.valueOf(hasil));
            }
        }
    }//GEN-LAST:event_konversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonverterPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonverterPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonverterPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonverterPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonverterPanjang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkan;
    private javax.swing.JComboBox<String> combobox1;
    private javax.swing.JComboBox<String> combobox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kembali;
    private javax.swing.JButton konversi;
    private javax.swing.JTextField panjang1;
    private javax.swing.JTextField panjang2;
    // End of variables declaration//GEN-END:variables
}
