/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversirupiah;

/**
 *
 * @author Alhamdulillah
 */

class component{
    public double rupiah;

    public double getRupiah() {
        return rupiah;
    }

    public void setRupiah(double rupiah) {
        this.rupiah = rupiah;
    }
}

public class KonversiRupiah extends javax.swing.JFrame {

    /**
     * Creates new form KonversiRupiah
     */
    public KonversiRupiah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();
        konversi = new javax.swing.JButton();
        matauangrupiah = new javax.swing.JTextField();
        matauangasing = new javax.swing.JTextField();
        combobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 140, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Konverter Rupiah");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prop/Coins.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 262, -1, -1));

        bersihkan.setBackground(new java.awt.Color(255, 153, 0));
        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });
        jPanel1.add(bersihkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 160, -1, -1));

        konversi.setBackground(new java.awt.Color(255, 153, 0));
        konversi.setText("Konversi");
        konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiActionPerformed(evt);
            }
        });
        jPanel1.add(konversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 160, -1, -1));
        jPanel1.add(matauangrupiah, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 120, 247, -1));
        jPanel1.add(matauangasing, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 203, 247, -1));

        combobox.setBackground(new java.awt.Color(255, 153, 0));
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dollar Singapore", "Ringgit Malaysia", "Riyal Saudi", "Rubel", "Pounsterling", "US Dollar" }));
        jPanel1.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 203, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prop/05a59f5d-547e-4bd8-9c97-cd1e3b0ae232.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 510, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        matauangrupiah.setText("");
        matauangasing.setText("");
    }//GEN-LAST:event_bersihkanActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void konversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiActionPerformed
        String box1 = (String)combobox.getSelectedItem();
        component komponen = new component();
        komponen.setRupiah(Double.parseDouble(matauangrupiah.getText()));
        
        if (box1.equals("US Dollar")){
            double USDollar = (double)(komponen.getRupiah() / 16303.00);
            
            matauangasing.setText(String.valueOf(USDollar));
        } else if (box1.equals("Ringgit Malaysia")){
            double RinggitMalaysia = (double)(komponen.getRupiah() / 3454.39);
            
            matauangasing.setText(String.valueOf(RinggitMalaysia));
        } else if (box1.equals("Riyal Saudi")){
            double RiyalSaudi = (double)(komponen.getRupiah() / 4346.95);
            
            matauangasing.setText(String.valueOf(RiyalSaudi));
        } else if (box1.equals("Dollar Singapore")){
            double DollarSingapore = (double)(komponen.getRupiah() / 12047.74);
         
            matauangasing.setText(String.valueOf(DollarSingapore));
        } else if (box1.equals("Rubel")){
            double Rubel = (double)(komponen.getRupiah() / 182.65);
            
            matauangasing.setText(String.valueOf(Rubel));
        } else if (box1.equals("Pounsterling")){
            double Pounsterling = (double)(komponen.getRupiah() / 20769.37);
            
            matauangasing.setText(String.valueOf(Pounsterling));
        }
    }//GEN-LAST:event_konversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiRupiah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiRupiah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiRupiah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiRupiah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiRupiah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkan;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kembali;
    private javax.swing.JButton konversi;
    private javax.swing.JTextField matauangasing;
    private javax.swing.JTextField matauangrupiah;
    // End of variables declaration//GEN-END:variables
}
