/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversirupiah;

/**
 *
 * @author Alhamdulillah
 */

class compo{
    public double awal;

    public double getAwal() {
        return awal;
    }

    public void setAwal(double awal) {
        this.awal = awal;
    }
    
}

public class KonversiBerat extends javax.swing.JFrame {

    /**
     * Creates new form KonversiBerat
     */
    public KonversiBerat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        berat1 = new javax.swing.JTextField();
        berat2 = new javax.swing.JTextField();
        bersihkan = new javax.swing.JButton();
        konversi = new javax.swing.JButton();
        combobox1 = new javax.swing.JComboBox<>();
        combobox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 177, 113));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(215, 181, 147));

        jLabel1.setBackground(new java.awt.Color(151, 96, 42));
        jLabel1.setFont(new java.awt.Font("Sitka Display", 0, 48)); // NOI18N
        jLabel1.setText("Konverter Berat");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prop/Weight.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 262, -1, -1));

        berat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berat1ActionPerformed(evt);
            }
        });
        jPanel1.add(berat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 131, 300, -1));

        berat2.setToolTipText("");
        berat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berat2ActionPerformed(evt);
            }
        });
        jPanel1.add(berat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 209, 300, -1));

        bersihkan.setBackground(new java.awt.Color(215, 181, 147));
        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });
        jPanel1.add(bersihkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 166, -1, -1));

        konversi.setBackground(new java.awt.Color(215, 181, 147));
        konversi.setText("Konversi");
        konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiActionPerformed(evt);
            }
        });
        jPanel1.add(konversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 166, -1, -1));

        combobox1.setBackground(new java.awt.Color(199, 153, 106));
        combobox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "HG", "DAG", "G", "DG", "CG", "MG" }));
        jPanel1.add(combobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 131, -1, -1));

        combobox2.setBackground(new java.awt.Color(199, 153, 106));
        combobox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "HG", "DAG", "G", "DG", "CG", "MG" }));
        jPanel1.add(combobox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 209, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prop/56462c6f-fb73-41ad-8ddd-51d407ec1484.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 50, 520, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void berat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_berat1ActionPerformed

    private void berat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_berat2ActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        berat1.setText("");
        berat2.setText("");
    }//GEN-LAST:event_bersihkanActionPerformed

    private void konversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiActionPerformed
        String box1 = (String) combobox1.getSelectedItem();
        String box2 = (String) combobox2.getSelectedItem();
        compo komponen = new compo();
        komponen.setAwal(Double.parseDouble(berat1.getText()));
        
        if (box1.equals("KG")){
            if (box2.equals("KG")){
                double hasil = komponen.getAwal();
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("HG")){
                double hasil = komponen.getAwal() * 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAG")){
                double hasil = komponen.getAwal() * 100;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("G")){
                double hasil = komponen.getAwal() * 1000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DG")){
                double hasil = komponen.getAwal() * 10000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("CG")){
                double hasil = komponen.getAwal() * 100000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("MG")){
                double hasil = komponen.getAwal() * 1000000;
                berat2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("HG")){
            if (box2.equals("KG")){
                double hasil = komponen.getAwal() / 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("HG")){
                double hasil = komponen.getAwal();
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAG")){
                double hasil = komponen.getAwal() * 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("G")){
                double hasil = komponen.getAwal() * 100;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DG")){
                double hasil = komponen.getAwal() * 1000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("CG")){
                double hasil = komponen.getAwal() * 10000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("MG")){
                double hasil = komponen.getAwal() * 100000;
                berat2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("DAG")){
            if (box2.equals("KG")){
                double hasil = komponen.getAwal() / 100;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("HG")){
                double hasil = komponen.getAwal() / 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAG")){
                double hasil = komponen.getAwal();
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("G")){
                double hasil = komponen.getAwal() * 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DG")){
                double hasil = komponen.getAwal() * 100;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("CG")){
                double hasil = komponen.getAwal() * 1000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("MG")){
                double hasil = komponen.getAwal() * 10000;
                berat2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("G")){
            if (box2.equals("KG")){
                double hasil = komponen.getAwal() / 1000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("HG")){
                double hasil = komponen.getAwal() / 100;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAG")){
                double hasil = komponen.getAwal() / 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("G")){
                double hasil = komponen.getAwal();
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DG")){
                double hasil = komponen.getAwal() * 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("CG")){
                double hasil = komponen.getAwal() * 100;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("MG")){
                double hasil = komponen.getAwal() * 1000;
                berat2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("DG")){
            if (box2.equals("KG")){
                double hasil = komponen.getAwal() / 10000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("HG")){
                double hasil = komponen.getAwal() / 1000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAG")){
                double hasil = komponen.getAwal() / 100;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("G")){
                double hasil = komponen.getAwal() / 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DG")){
                double hasil = komponen.getAwal();
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("CG")){
                double hasil = komponen.getAwal() * 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("MG")){
                double hasil = komponen.getAwal() * 100;
                berat2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("CG")){
            if (box2.equals("KG")){
                double hasil = komponen.getAwal() / 100000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("HG")){
                double hasil = komponen.getAwal() / 10000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAG")){
                double hasil = komponen.getAwal() / 1000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("G")){
                double hasil = komponen.getAwal() / 100;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DG")){
                double hasil = komponen.getAwal() / 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("CG")){
                double hasil = komponen.getAwal();
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("MG")){
                double hasil = komponen.getAwal() * 10;
                berat2.setText(String.valueOf(hasil));
            }
        } else if (box1.equals("MG")){
            if (box2.equals("KG")){
                double hasil = komponen.getAwal() / 1000000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("HG")){
                double hasil = komponen.getAwal() / 100000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DAG")){
                double hasil = komponen.getAwal() / 10000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("G")){
                double hasil = komponen.getAwal() / 1000;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("DG")){
                double hasil = komponen.getAwal() / 100;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("CG")){
                double hasil = komponen.getAwal() / 10;
                berat2.setText(String.valueOf(hasil));
            } else if (box2.equals("MG")){
                double hasil = komponen.getAwal();
                berat2.setText(String.valueOf(hasil));
            }
        }
    }//GEN-LAST:event_konversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiBerat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiBerat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiBerat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiBerat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiBerat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat1;
    private javax.swing.JTextField berat2;
    private javax.swing.JButton bersihkan;
    private javax.swing.JComboBox<String> combobox1;
    private javax.swing.JComboBox<String> combobox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kembali;
    private javax.swing.JButton konversi;
    // End of variables declaration//GEN-END:variables
}
